version: '3.8'

services:
  rag-api:
    container_name: rag-api
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - rag-api:latest
    image: rag-api:latest
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - qdrant

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["sh", "/entrypoint.sh"]

volumes:
  qdrant_data:
  ollama_data: